version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
      time: "01:00"
    commit-message:
      prefix: "terraform "
      include: scope

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
      time: "02:00"
    commit-message:
      prefix: "github actions "
      include: scope

  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
      time: "03:00"
    commit-message:
      prefix: "pip "
      include: scope
