name: checkov

on:
  workflow_call:

jobs:
  scan:
    permissions:
      contents: read # for actions/checkout to fetch code

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform
