
name: TFLINT 

on:
  push:
    branches: [ main ]
  # Allows you to trigger it manually.
  workflow_dispatch:

jobs:
  tflint-checks:
    runs-on: ubuntu-latest
    steps:
    # checkout codebase
    - uses: actions/checkout@v3
      name: Checkout
      with:
        fetch-depth: 1

    # TFLint - Terraform Check
    - uses: actions/cache@v3
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        tflint_version: latest

    # Print TFLint version
    - name: Show version
      run: tflint --version

    # Install plugins
    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

    # Run tflint command in each directory recursively # use --force if you want to continue with workflow although errors are there
    - name: Run TFLint
      run: tflint -f compact --recursive