name: Invoke Branch Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tflint:
        description: 'Run TFLint against your branch?'
        type: choice
        options:
        - 'yes'
        - 'no'
        default: 'yes'
        required: true

jobs:

  call-tflint-workflow:
    if: ${{ inputs.tflint }} == 'yes'
    uses: ./.github/workflows/tflint_workflow.yaml
